### ISSUE TITLE
Research Reliable Resources

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#18]

**Comment by ElMarcoPollo** [comment]
So for my topic "Ways Our Online Data Can Be Compromised, And How To Minimize The Damage" I found a few reliable resources for information:

1. Electronic Frontier Foundation - https://www.eff.org/
2. National Cyber Security Centre - https://www.ncsc.gov.uk
3. Electronic Privacy Information Center - https://epic.org/
4. Federal Trade Commission - https://consumer.ftc.gov/articles/protect-your-personal-information-and-data
