### ISSUE TITLE
Define Content Categories

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#19]

**Comment by davidOrtega18** [comment]
I think here we should all brain storm.

**Comment by heyhaylan** [comment]
So far we have two types of content for the website - articles like before and also pages about tech companies in the greater seattle area as a resource for someone just out of school looking for where to apply for jobs. the type of content on each company page is listed in the "define company info" task. If you have ideas for that go and post them over there. Marshall is making an html page template so people can research companies and then plug the info into his template.
