### ISSUE TITLE
Define company info pages

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#26]
Company name:
Location: 
Mission statement:
IT roles:
Glassdoor rating:
Benefits: 

Goal is to provide information about tech companies in the greater seattle area as a resource for someone looking for work. 

**Please add a comment to this issue to add anything to the information you would like to see on the company page.**

**Comment by heyhaylan** [comment]
+ link to jobs page for company

**Comment by ElMarcoPollo** [comment]
1. Microsoft
2. Amazon
3. Google (Kirkland)
4. Facebook
5. Adobe (Fremont)
6. Rokt
7. Tableau Software
8. Expedia
