### ISSUE TITLE
Create list of tech companies in greater Seattle area

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#33]
This results of this task will be used by others to start their research. We currently already have Amazon and Microsoft so you can leave those off this list.

**Comment by ElMarcoPollo** [comment]
1. Microsoft
2. Amazon
3. Google (Kirkland)
4. Facebook
5. Adobe (Fremont)
6. Rokt
7. Tableau Software
9. Expedia

**Comment by heyhaylan** [comment]
Valve
Nintendo
Warner Bros. Discovery
University of Washington
