### ISSUE TITLE
Research Company - Google

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#39]
Company name:
Location:
Mission statement:
IT roles:
Glassdoor rating:
Benefits:

Link to jobs/careers page.

**Comment by ElMarcoPollo** [comment]
* Company name : Google
* Location: Queen Anne, Fremont, Kirkland
* Mission statement:  "To organize the world’s information and make it universally accessible and useful."
* Careers:
  * Software Engineer
  * Product Manager
  * Data Scientist
  * UX/UI Designer
  * Test Engineer
* Unique Benefits:
   * Onsite wellness centers
   * Advocacy for transgender employees
   * Menopause Benefits
   * Four "work from anywhere" weeks per year
   * On-site snacks and meals
* Glassdoor rating/link
   * [Google | Glassdoor](https://www.glassdoor.com/Overview/Working-at-Google-EI_IE9079.11,17.htm)
* Link to jobs page for company
  * [Google Careers](https://www.google.com/about/careers/applications/)

**Comment by ElMarcoPollo** [comment]
I've copied this information to the [wiki page](https://github.com/Elias-Carr/IT115Team2/wiki/Website-Content-%E2%80%90-Company-Pages#google).
