### ISSUE TITLE
Research Company - Adobe

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#41]
Company name:
Location:
Mission statement:
IT roles:
Glassdoor rating:
Benefits:

Link to jobs/careers page.

**Comment by Elias-Carr** [comment]
Company name: Adobe
Location: Seattle
Mission statement: "To change the world through digital experiences."
IT roles:
- Business Development
- Engineering
- Intern-Technical
- Engineering Program Management
- Product Security Engineering
- Software Development Engineering
Glassdoor rating:
https://www.glassdoor.com/Reviews/Adobe-Seattle-Reviews-EI_IE1090.0,5_IL.6,13_IM781.htm
Benefits:
- Family support
- Commuter benefits
- Discounts, social impact, and awards
- Education benefits. College Coach
- Dependent Care Flexible Spending Account (FSA)
- Pet services
- Legal insurance.
- Travel support.
Link to jobs/careers page.
https://www.adobe.com/careers.html
