### ISSUE TITLE
Research Company - Nintendo of America

### ISSUE THREAD

**Issue by heyhaylan** [Elias-Carr/IT115Team2#46]
Company name:
Location:
Mission statement:
IT roles:
Glassdoor rating:
Benefits:

Link to jobs/careers page.

**Comment by ElMarcoPollo** [comment]
* Company name : Nintendo of America
* Location: Redmond
* Mission statement:  "To create smiles through unique entertainment experiences."
* Careers:
  * Software Engineer
  * Systems Administrator
  * Web Developer
  * Database Administrator
  * Network Engineer
* Unique Benefits:
   * Tuition reimbursement
   * Redmond Health & Wellness Center
   * Family-forming assistance (fertility, adoption, surrogacy support)
   * Employee discounts on Nintendo products
   * Free or subsidized transit programs
* Glassdoor rating/link
   * [Nintendo of America | Glassdoor](https://www.glassdoor.com/Reviews/Nintendo-of-America-Reviews-E4173.htm)
* Link to jobs page for company
  * [Nintendo of America Careers](https://careers.nintendo.com/job-openings/)

**Comment by ElMarcoPollo** [comment]
https://github.com/Elias-Carr/IT115Team2/wiki/Website-Content-%E2%80%90-Company-Pages#nintendo-of-america
