### ISSUE TITLE
Backlog - Complete Research for Companies

### ISSUE THREAD

**Issue by ElMarcoPollo** [Elias-Carr/IT115Team2#52]
- Google
- Meta
- Adobe
- Rokt
- Tableau Software
- Expedia
- Valve
- Nintendo of America
- Warn Bros. Discovery

**Comment by ElMarcoPollo** [comment]
Let's divvy up the company research between the four of us, so two each?

Everyone can reference the wiki for the information needed for each page:
https://github.com/Elias-Carr/IT115Team2/wiki/Website-Content-%E2%80%90-Company-Pages#company-pages-template

(I encourage everyone to add to the list of information points, but keep in mind that they will need to be updated on the html template file)

**Comment by heyhaylan** [comment]
Looks like we just have 2 companies left, which have their own tasks in the to do section.

**Comment by heyhaylan** [comment]
I'm going to close this issue since I broke it down into smaller tasks.
